openai_api.settings:
  type: config_object
  label: 'OpenAI API settings'
  mapping:
    api_token:
      type: string
      label: 'OpenAI token'
    api_url:
      type: string
      label: 'OpenAI url'
