openai_embeddings.settings:
  type: config_object
  label: 'Embeddings settings'
  mapping:
    node_types:
      type: mapping
      label: 'Enabled Node types'
      sequence:
        type: string
        label: 'Node type'
    model:
      type: string
      label: 'OpenAI model to use'
