openai_embeddings.settings:
  type: config_object
  label: 'Embeddings settings'
  mapping:
    entity_types:
      type: sequence
      label: 'Enabled entity types and their bundles.'
      sequence:
        type: sequence
        label: 'Entity type'
        sequence:
          type: sequence
          label: 'Bundle'
    node_types:
      type: mapping
      label: 'Enabled Node types'
      sequence:
        type: string
        label: 'Node type'
    model:
      type: string
      label: 'OpenAI model to use'
